from colorama import Fore, Back, Style
import numpy as np



#GAME PROPERTIES
FRAME_TIME = 0.08
FRAME_RATE = 100000
LIVES = 3


#WINDOW PROPERTIES
BOARD_HEIGHT = 50
BOARD_WIDTH = 80
BG_COLOR = Back.BLACK
BORDER_COLOR = Fore.WHITE


#BALL PROPERTIES
BALL_VELOCITY =  np.array([2,4])
BALL_COLOR = Fore.GREEN
BALL_SPRITE = '⬤'
BALL_STRENGTH = 1

#PADDLE PROPERTIES
PADDLE_SIZE = [1,16]
PADDLE_COLOR = Fore.WHITE
PADDLE_VELOCITY =  np.array([0,5])
PADDLE_SPRITE = '▒'